### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by yolile** [open-contracting/scrapy-log-analyzer#11]
The library currently has:

- crawl_time
- is_finished
- item_counts
- spider_arguments
- is_complete
- error_rate (but using `File` vs `FileError`)

As per https://kingfisher-collect.readthedocs.io/en/latest/logs.html, https://github.com/open-contracting/kingfisher-collect/issues/531, https://github.com/open-contracting/kingfisher-collect/issues/1058 and https://github.com/open-contracting/kingfisher-collect/issues/1055 I think we need to add:

1. drop_rate: `item_dropped_count` vs `item_scraped_count`
1. duplicate_request_rate: `dupefilter/filtered` vs `downloader/request_count` https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-number-of-duplicate-requests
1. invalid_json_rate: `invalid_json_count` vs `item_scraped_count`
1. finish_reason: cancelled, finished, etc as documented https://kingfisher-collect.readthedocs.io/en/latest/logs.html#check-the-reason-for-closing-the-spider
1. errors_count: https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-numbers-of-error-messages
1. errors_list: https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-numbers-of-error-messages
1. response_status_counts: https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-numbers-of-error-response-status-codes
1. exception_count: https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-numbers-of-downloader-exceptions
1. retry_times_reached: https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-number-of-requests-for-which-the-maximum-number-of-retries-was-reached

@jpmckinney any others? Do you agree with implementing all of them?

**Comment by yolile** [comment]
(1) ok 
(2) I've edited the issue, but from https://kingfisher-collect.readthedocs.io/en/latest/logs.html#read-the-number-of-duplicate-requests
(4) Ok

(3) and (5-6) I'm not sure whether we can do anything automatically with this information. But, it would be useful to collect and report the messages and counts.

We should use this information to report the issues with the partners. If we use FileError for everything we would need a way to differentiate invalid JSON errors from failed requests, etc, so that we can report the issue properly to the partner.

(7)(8)(9) ok

**Comment by jpmckinney** [comment]
Aha - (2) is maybe more a programming error, whereas (1) is a publisher error. It can be reported for information.

Okay, let's not change (3) to a FileError (as-is, it still gets logged in the crawl log for regular Kingfisher Collect users), but in terms of calculating `error_rate`, we should include invalid JSON.

**Comment by jpmckinney** [comment]
For 6 we can use logparser as described at https://github.com/open-contracting/scrapy-log-analyzer/pull/14#issuecomment-2538810818

**Comment by yolile** [comment]
Hmm for drop items, looking at Kingfisher Collect, I see we drop items in 3 different scenarios;
- Sample (not relevant)
- Duplicates (not a reason for rejecting a collection for the registry but good for reporting to the partner)
- Invalid JSONs (good reason for rejecting a collection and already included in errors_rate)

So, the `drop_rate` won't be used for rejecting a collection, and the rate only, mixing duplicates and invalid JSONs, is not useful for reporting. 

Should we just remove `drop_rate` and check `item_dropped_count` and `invalid_json_count` individually as needed in https://github.com/open-contracting/kingfisher-collect/issues/531 instead?

**Comment by jpmckinney** [comment]
Yes, makes sense
